# Generated by Django 4.2.6 on 2023-11-10 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.png', upload_to='products', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_type',
            field=models.CharField(choices=[('unitario', 'Precio Unitario'), ('media-doc', 'Media Docena'), ('docena', 'Docena'), ('por-kilo', 'Kilo')], default='unitario', max_length=9),
        ),
    ]
