# Generated by Django 5.0 on 2023-12-29 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['name'], 'verbose_name': 'Tipo precio', 'verbose_name_plural': 'Tipo precios'},
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.price', verbose_name='Tipo de Precio'),
        ),
    ]
